"""Add email, curp, and DOB to students and teachers

Revision ID: 4a0ea36e1cfb
Revises: e1f2a3b4c5d6
Create Date: 2026-04-05 02:37:16.890395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0ea36e1cfb'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.String(), nullable=True))
    op.add_column('students', sa.Column('curp', sa.String(), nullable=True))
    op.add_column('students', sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
    op.add_column('teachers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('curp', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'fecha_nacimiento')
    op.drop_column('teachers', 'curp')
    op.drop_column('teachers', 'email')
    op.drop_column('students', 'fecha_nacimiento')
    op.drop_column('students', 'curp')
    op.drop_column('students', 'email')
    # ### end Alembic commands ###
