"""Add activo column to students

Revision ID: 921570c798a6
Revises: 4a0ea36e1cfb
Create Date: 2026-04-05 04:06:03.242726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921570c798a6'
down_revision: Union[str, None] = '4a0ea36e1cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable
    op.add_column('students', sa.Column('activo', sa.Boolean(), nullable=True))
    # 2. Set default value for existing rows
    op.execute("UPDATE students SET activo = true")
    # 3. Alter column to be NOT NULL
    op.alter_column('students', 'activo', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'activo')
    # ### end Alembic commands ###
