"""Add student status, group reference and parent curp

Revision ID: d739a31da9cb
Revises: 921570c798a6
Create Date: 2026-04-05 04:29:32.871918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd739a31da9cb'
down_revision: Union[str, None] = '921570c798a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create Enum type
    student_status = sa.Enum('activo', 'inactivo', 'graduado', name='student_status')
    student_status.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('curp', sa.String(), nullable=True))
    op.add_column('parents', sa.Column('telefono_trabajo', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'parents', ['curp'])
    op.add_column('students', sa.Column('current_group_id', sa.UUID(), nullable=True))
    
    # Add as nullable first
    op.add_column('students', sa.Column('status', student_status, nullable=True))
    # Update existing rows
    op.execute("UPDATE students SET status = 'activo'")
    # Make NOT NULL
    op.alter_column('students', 'status', nullable=False)
    
    op.create_foreign_key(None, 'students', 'groups', ['current_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'status')
    
    # Drop Enum type
    sa.Enum(name='student_status').drop(op.get_bind())
    
    op.drop_column('students', 'current_group_id')
    op.drop_constraint(None, 'parents', type_='unique')
    op.drop_column('parents', 'telefono_trabajo')
    op.drop_column('parents', 'curp')
    # ### end Alembic commands ###
