"""Add must_change_password to users

Revision ID: d7cb97a50725
Revises: d739a31da9cb
Create Date: 2026-04-05 06:19:18.272865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7cb97a50725'
down_revision: Union[str, None] = 'd739a31da9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=True))
    # 2. Set default value for existing rows
    op.execute("UPDATE users SET must_change_password = false")
    # 3. Alter column to be NOT NULL
    op.alter_column('users', 'must_change_password', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
